name: navigation_dots
description: Personalized Dot Navigation Dock
version: 1.0.0
homepage: https://github.com/sxdpz23/navigation_dots

environment:
  sdk: ">=2.15.1 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter: